### ISSUE TITLE
Death stranding localization files

### ISSUE THREAD

**Issue by YouKnow-sys** [REDxEYE/ProjectDecima_python#1]
Hi, do you have any plan for add support for export localization files?
if yes i think it better to script extract each language to separate files

**Comment by REDxEYE** [comment]
Yeah, it was added previously, but after a recent refactor extracting of languages was broken. 
I won't be adding some specific logic for extracting languages though, localization will be serialized to JSON as all other objects

**Comment by YouKnow-sys** [comment]
> Yeah, it was added previously, but after a recent refactor extracting of languages was broken.
> I won't be adding some specific logic for extracting languages though, localization will be serialized to JSON as all other objects

thanks for good work, i appreciate your work, you think how long it take to we can actually unpack and repack localization files?

**Comment by REDxEYE** [comment]
Project right now is aimed to file extraction and research, no repack/pack features are planned

**Comment by YouKnow-sys** [comment]
> Project right now is aimed to file extraction and research, no repack/pack features are planned

maybe in future?
its a very good and needed feature, with it, its possible to translate game into other unofficial language
